<!DOCTYPE html>
<html lang="en">

<head>
    <title></title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>

<body>

</body>
<script>

    /***
     * 1.promise 出现的原因
     *   1.为了解决异步回调问题
     *   2.为了解决信任问题  
     *   3.为了解决回调执行顺序问题
     *   4.为了解决捕捉错误的能力
     * 2.Promise
     *   概念：Promise是一个容器，里面放着一个在未来执行的事件（一般为异步操作）
     *   语法：Promise是一个对象，可以获取异步操作的消息
     * 3.特点
     *   1.有三种状态：pedding（等待中），fulfilled（已成功），rejected（已失败）
     *   2.状态的变化：
     *      2.1 从等待中到已成功
     *      2.2 从等到中到已失败
     *   3.一旦状态确定，便不再更改，状态凝固---》resolved，无论什么时候监听都是这样了
     *   4.promise返回的值无论是不是promise函数，最终都会被封装成promise函数进行返回，需要我们用.then进行获取其中的值
     *   5.链式调用
     * 4. 和事件循环的区别
     *   事件循环一旦错过，不会再被监听到
     *   Promise状态凝固，永远都可以被监听
     * 5.promise 的参数
     *      resolved ---》成功
     *      reject---》失败
      ***/



    const p = new Promise(function (resolve, reject) {
        setTimeout(function () {
            // let data = "我要休息"
            // resolve(data)
            let data1 = "我还不能休息，我要学习"
            reject(data1)
        }, 2000)
    })
    p.then(res => {
        console.log(res, "成功的回调");
    }).catch(err => {
        console.log(err, "失败的回调");
    })

    p.then(
        res => {
            console.log(res);
        },
        err => {
            console.log(err);
        }
    )





    console.log("分割------------------------");




    // const p = new Promise(function (resolve, reject) {
    //     setTimeout(function () {
    //         // let data = "我要休息"
    //         // resolve(data)
    //         let data1 = "我还不能休息，我要学习"
    //         reject(data1)
    //     }, 2000)
    // })
    // p.then(res => {
    //     console.log(res, "成功的回调");
    // }).catch(err => {
    //     console.log(err, "失败的回调");
    // })

    // p.then(
    //     res=>{
    //         console.log(res);
    //     },
    //     err=>{
    //         console.log(err);
    //     }
    // )

    console.log("分割------------------------");


    // const p = new Promise(function (resolve, reject) {
    //     setTimeout(function () {
    //         // let data = "我要休息"
    //         // resolve(data)
    //         let data1 = "我还不能休息，我要学习"
    //         reject(data1)
    //     }, 2000)
    // })
    // p.then(res => {
    //     console.log(res, "成功的回调");
    // }).catch(err => {
    //     console.log(err, "失败的回调");
    // })

    // p.then(
    //     res=>{
    //         console.log(res);
    //     },
    //     err=>{
    //         console.log(err);
    //     }
    // )
</script>

</html>